// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzQwaA4pyeE_zkzU3ouS73zoqx_7Aq_BI',
    appId: '1:981962187089:web:fc8b204dcc48a907edf370',
    messagingSenderId: '981962187089',
    projectId: 'socialmediaapp-6bd47',
    authDomain: 'socialmediaapp-6bd47.firebaseapp.com',
    storageBucket: 'socialmediaapp-6bd47.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfX0Yd2VvynAfkjqyRstCORztkA1-RTEg',
    appId: '1:981962187089:android:ffdf41c810ffd1f8edf370',
    messagingSenderId: '981962187089',
    projectId: 'socialmediaapp-6bd47',
    storageBucket: 'socialmediaapp-6bd47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY75WE4qIfu-NYdocl0OUKScSpAHDH8_4',
    appId: '1:981962187089:ios:0610cbcbb64b096eedf370',
    messagingSenderId: '981962187089',
    projectId: 'socialmediaapp-6bd47',
    storageBucket: 'socialmediaapp-6bd47.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY75WE4qIfu-NYdocl0OUKScSpAHDH8_4',
    appId: '1:981962187089:ios:0610cbcbb64b096eedf370',
    messagingSenderId: '981962187089',
    projectId: 'socialmediaapp-6bd47',
    storageBucket: 'socialmediaapp-6bd47.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzQwaA4pyeE_zkzU3ouS73zoqx_7Aq_BI',
    appId: '1:981962187089:web:de6cd23c8dcd1f6eedf370',
    messagingSenderId: '981962187089',
    projectId: 'socialmediaapp-6bd47',
    authDomain: 'socialmediaapp-6bd47.firebaseapp.com',
    storageBucket: 'socialmediaapp-6bd47.firebasestorage.app',
  );
}
